name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.9
      with:
        name: programa              

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with: 
        username: victorhugo01234
        password: ${{ secrets.PASSWORD_DOCKER }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: victorhugo01234/go_ci:${{ github.ref_name }}
